CREATE TABLE IF NOT EXISTS documents (
    id VARCHAR PRIMARY KEY,
    object_key VARCHAR NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    owner_id VARCHAR,
    FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS metadata (
    id VARCHAR PRIMARY KEY,
    name VARCHAR NOT NULL,
    document_id VARCHAR NOT NULL,
    mime_type VARCHAR NOT NULL,
    size INT NOT NULL,
    extension VARCHAR NOT NULL,
    FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE ON UPDATE CASCADE
);