name: tag & release

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write

jobs:
  tag_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Create and push tag
        env:
          NEW_TAG: ${{ steps.semver.outputs.next }}
          MERGE_SHA: ${{ github.event.pull_request.merge_commit_sha }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git fetch origin main
          git checkout main
          git pull origin main

          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PR_URL="${{ github.event.pull_request.html_url }}"

          git tag -a "${NEW_TAG}" "${MERGE_SHA}" -m "Release ${NEW_TAG}

          PR #${PR_NUMBER}: ${PR_TITLE}
          ${PR_URL}

          Merged commit: ${MERGE_SHA}"

          git push origin "${NEW_TAG}"
          
      - name: Create Release
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
